footprint: [[-0.6, -0.35], [0.6, -0.35], [0.6, 0.35], [-0.6, 0.35]]
global_frame: map
transform_tolerance: 2
plugins:
   - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

inflation_layer:
  inflation_radius: 0.15