arm_ik_controller:
  type: rover_ik/IKJointController
  joints:
    - arm_slide_pole_to_arm_slider_unit
    - arm_slider_unit_to_arm_xy_pole
    - arm_inner_to_arm_outer
    - arm_outer_to_grip_spin
  gains:
    arm_slider_unit_to_arm_xy_pole: {p: 170.0, d: 1.4, i: 0, i_clamp: 1}
    arm_inner_to_arm_outer: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}
    arm_slide_pole_to_arm_slider_unit: {p: 4075.0, d: 0, i: 0, i_clamp: 0}
    arm_outer_to_gripper_spin: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}
  base_link: base_link
  tip_link: grip_spin

arm_moveit_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_slide_pole_to_arm_slider_unit
    - arm_slider_unit_to_arm_xy_pole
    - arm_inner_to_arm_outer
    - arm_outer_to_gripper_spin
  gains:
    arm_slider_unit_to_arm_xy_pole: {p: 170.0, d: 1.4, i: 0, i_clamp: 1}
    arm_inner_to_arm_outer: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}
    arm_slide_pole_to_arm_slider_unit: {p: 4075.0, d: 0, i: 0, i_clamp: 0}
    arm_outer_to_gripper_spin: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}

arm_manual_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - arm_slide_pole_to_arm_slider_unit
    - arm_slider_unit_to_arm_xy_pole
    - arm_inner_to_arm_outer
    - arm_outer_to_grip_spin
