
# all joints that have potentiometers
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# wheels
left_wheels_controller:
  type: rover_drive/DriveSideController
  joints:
    - leg_to_wheel_front_left
    - leg_to_wheel_center_left
    - leg_to_wheel_back_left

right_wheels_controller:
  type: rover_drive/DriveSideController
  joints:
    - leg_to_wheel_front_right
    - leg_to_wheel_center_right
    - leg_to_wheel_back_right

# wheel "skid" drive. (does odom too!)
wheel_diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['leg_to_wheel_front_left', 'leg_to_wheel_center_left', 'leg_to_wheel_back_left']
  right_wheel: ['leg_to_wheel_front_right', 'leg_to_wheel_center_right', 'leg_to_wheel_back_right']
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.3, 0.3, 0.3, 1000000.0, 1000000.0, 0.03]

#  enable_odom_tf: false

arm_moveit_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_slide_pole_to_arm_slider_unit
    - arm_slider_unit_to_arm_xy_pole
    - arm_inner_to_arm_outer
    - arm_outer_to_gripper_spin
  gains:
    arm_slider_unit_to_arm_xy_pole: {p: 170.0, d: 1.4, i: 0, i_clamp: 1}
    arm_inner_to_arm_outer: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}
    arm_slide_pole_to_arm_slider_unit: {p: 4075.0, d: 0, i: 0, i_clamp: 0}
    arm_outer_to_gripper_spin: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}

arm_ik_controller:
  type: rover_ik/IKJointController
  joints:
    - arm_slide_pole_to_arm_slider_unit
    - arm_slider_unit_to_arm_xy_pole
    - arm_inner_to_arm_outer
    - arm_outer_to_grip_spin
  gains:
    arm_slider_unit_to_arm_xy_pole: {p: 170.0, d: 1.4, i: 0, i_clamp: 1}
    arm_inner_to_arm_outer: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}
    arm_slide_pole_to_arm_slider_unit: {p: 4075.0, d: 0, i: 0, i_clamp: 0}
    arm_outer_to_gripper_spin: {p: 170.0, d: 0.5, i: 0, i_clamp: 1}
  base_link: base_link
  tip_link: grip_spin